@startuml Singleton
title Singleton pattern

class Singleton <<final class>> {
    -{static} instance : Singleton
    - Singleton()
    +{static} getInstance() : Singleton
}

Singleton --> Singleton:instance
@enduml
